// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ActionQueue struct {
	_tab flatbuffers.Table
}

func GetRootAsActionQueue(buf []byte, offset flatbuffers.UOffsetT) *ActionQueue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ActionQueue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ActionQueue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ActionQueue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ActionQueue) User() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ActionQueue) Actions(obj *Action, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ActionQueue) ActionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ActionQueue) Turn() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ActionQueue) MutateTurn(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *ActionQueue) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ActionQueue) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func ActionQueueStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ActionQueueAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(user), 0)
}
func ActionQueueAddActions(builder *flatbuffers.Builder, actions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(actions), 0)
}
func ActionQueueStartActionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ActionQueueAddTurn(builder *flatbuffers.Builder, turn int32) {
	builder.PrependInt32Slot(2, turn, 0)
}
func ActionQueueAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(3, error, 0)
}
func ActionQueueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
