// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Authentication struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthentication(buf []byte, offset flatbuffers.UOffsetT) *Authentication {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Authentication{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Authentication) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Authentication) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Authentication) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Authentication) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Authentication) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func AuthenticationStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AuthenticationAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func AuthenticationAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(1, error, 0)
}
func AuthenticationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
