// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DestroyedRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsDestroyedRoom(buf []byte, offset flatbuffers.UOffsetT) *DestroyedRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DestroyedRoom{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DestroyedRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DestroyedRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DestroyedRoom) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DestroyedRoom) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func DestroyedRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DestroyedRoomAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(0, error, 0)
}
func DestroyedRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
