// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameStart struct {
	_tab flatbuffers.Table
}

func GetRootAsGameStart(buf []byte, offset flatbuffers.UOffsetT) *GameStart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameStart{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GameStart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameStart) Table() flatbuffers.Table {
	return rcv._tab
}

func GameStartStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GameStartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
