// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameStart struct {
	_tab flatbuffers.Table
}

func GetRootAsGameStart(buf []byte, offset flatbuffers.UOffsetT) *GameStart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameStart{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GameStart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameStart) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GameStart) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameStart) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *GameStart) Seed() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameStart) MutateSeed(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func GameStartStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GameStartAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(0, error, 0)
}
func GameStartAddSeed(builder *flatbuffers.Builder, seed int64) {
	builder.PrependInt64Slot(1, seed, 0)
}
func GameStartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
