// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HttpException struct {
	_tab flatbuffers.Table
}

func GetRootAsHttpException(buf []byte, offset flatbuffers.UOffsetT) *HttpException {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HttpException{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HttpException) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HttpException) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HttpException) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HttpException) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func HttpExceptionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HttpExceptionAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(0, error, 0)
}
func HttpExceptionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
