// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InGameChat struct {
	_tab flatbuffers.Table
}

func GetRootAsInGameChat(buf []byte, offset flatbuffers.UOffsetT) *InGameChat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InGameChat{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *InGameChat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InGameChat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InGameChat) Turn() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InGameChat) MutateTurn(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *InGameChat) Frame() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InGameChat) MutateFrame(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *InGameChat) Sequence() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InGameChat) MutateSequence(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *InGameChat) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InGameChat) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InGameChat) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func InGameChatStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func InGameChatAddTurn(builder *flatbuffers.Builder, turn int32) {
	builder.PrependInt32Slot(0, turn, 0)
}
func InGameChatAddFrame(builder *flatbuffers.Builder, frame int32) {
	builder.PrependInt32Slot(1, frame, 0)
}
func InGameChatAddSequence(builder *flatbuffers.Builder, sequence int32) {
	builder.PrependInt32Slot(2, sequence, 0)
}
func InGameChatAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(message), 0)
}
func InGameChatAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(4, error, 0)
}
func InGameChatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
