// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KickedRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsKickedRoom(buf []byte, offset flatbuffers.UOffsetT) *KickedRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KickedRoom{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *KickedRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KickedRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KickedRoom) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KickedRoom) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func KickedRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KickedRoomAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(0, error, 0)
}
func KickedRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
