// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Route struct {
	_tab flatbuffers.Table
}

func GetRootAsRoute(buf []byte, offset flatbuffers.UOffsetT) *Route {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Route{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Route) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Route) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Route) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Route) Port() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Route) MutatePort(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Route) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Route) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func RouteStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RouteAddHost(builder *flatbuffers.Builder, host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(host), 0)
}
func RouteAddPort(builder *flatbuffers.Builder, port uint32) {
	builder.PrependUint32Slot(1, port, 0)
}
func RouteAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(2, error, 0)
}
func RouteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
