// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RouteCreate struct {
	_tab flatbuffers.Table
}

func GetRootAsRouteCreate(buf []byte, offset flatbuffers.UOffsetT) *RouteCreate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RouteCreate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RouteCreate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RouteCreate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RouteCreate) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RouteCreate) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RouteCreate) Port() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RouteCreate) MutatePort(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *RouteCreate) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RouteCreate) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func RouteCreateStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RouteCreateAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func RouteCreateAddHost(builder *flatbuffers.Builder, host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(host), 0)
}
func RouteCreateAddPort(builder *flatbuffers.Builder, port uint32) {
	builder.PrependUint32Slot(2, port, 0)
}
func RouteCreateAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(3, error, 0)
}
func RouteCreateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
