// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Request
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Resume : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Resume GetRootAsResume(ByteBuffer _bb) { return GetRootAsResume(_bb, new Resume()); }
  public static Resume GetRootAsResume(ByteBuffer _bb, Resume obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Resume __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartResume(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<FlatBuffer.Request.Resume> EndResume(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Request.Resume>(o);
  }
};


}
