// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Request
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RouteCreate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static RouteCreate GetRootAsRouteCreate(ByteBuffer _bb) { return GetRootAsRouteCreate(_bb, new RouteCreate()); }
  public static RouteCreate GetRootAsRouteCreate(ByteBuffer _bb, RouteCreate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RouteCreate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRouteCreate(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<FlatBuffer.Request.RouteCreate> EndRouteCreate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Request.RouteCreate>(o);
  }
};


}
