// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Request
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct JoinRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb) { return GetRootAsJoinRoom(_bb, new JoinRoom()); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb, JoinRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatBuffer.Request.JoinRoom> CreateJoinRoom(FlatBufferBuilder builder,
      uint id = 0) {
    builder.StartTable(1);
    JoinRoom.AddId(builder, id);
    return JoinRoom.EndJoinRoom(builder);
  }

  public static void StartJoinRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static Offset<FlatBuffer.Request.JoinRoom> EndJoinRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Request.JoinRoom>(o);
  }
};


}
