// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Response
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GameStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static GameStart GetRootAsGameStart(ByteBuffer _bb) { return GetRootAsGameStart(_bb, new GameStart()); }
  public static GameStart GetRootAsGameStart(ByteBuffer _bb, GameStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Seed { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public uint Error { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatBuffer.Response.GameStart> CreateGameStart(FlatBufferBuilder builder,
      long seed = 0,
      uint error = 0) {
    builder.StartTable(2);
    GameStart.AddSeed(builder, seed);
    GameStart.AddError(builder, error);
    return GameStart.EndGameStart(builder);
  }

  public static void StartGameStart(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSeed(FlatBufferBuilder builder, long seed) { builder.AddLong(0, seed, 0); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(1, error, 0); }
  public static Offset<FlatBuffer.Response.GameStart> EndGameStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Response.GameStart>(o);
  }
};


}
