// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Response
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CreateRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CreateRoom GetRootAsCreateRoom(ByteBuffer _bb) { return GetRootAsCreateRoom(_bb, new CreateRoom()); }
  public static CreateRoom GetRootAsCreateRoom(ByteBuffer _bb, CreateRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CreateRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatBuffer.Response.CreateRoom> CreateCreateRoom(FlatBufferBuilder builder,
      uint id = 0) {
    builder.StartTable(1);
    CreateRoom.AddId(builder, id);
    return CreateRoom.EndCreateRoom(builder);
  }

  public static void StartCreateRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static Offset<FlatBuffer.Response.CreateRoom> EndCreateRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Response.CreateRoom>(o);
  }
};


}
