// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Response
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct JoinRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb) { return GetRootAsJoinRoom(_bb, new JoinRoom()); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb, JoinRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Users(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(__p.__vector(o) + j * 8) : (ulong)0; }
  public int UsersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ulong> GetUsersBytes() { return __p.__vector_as_span<ulong>(4, 8); }
#else
  public ArraySegment<byte>? GetUsersBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public ulong[] GetUsersArray() { return __p.__vector_as_array<ulong>(4); }

  public static Offset<FlatBuffer.Response.JoinRoom> CreateJoinRoom(FlatBufferBuilder builder,
      VectorOffset usersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    JoinRoom.AddUsers(builder, usersOffset);
    return JoinRoom.EndJoinRoom(builder);
  }

  public static void StartJoinRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUsers(FlatBufferBuilder builder, VectorOffset usersOffset) { builder.AddOffset(0, usersOffset.Value, 0); }
  public static VectorOffset CreateUsersVector(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddUlong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUsersVectorBlock(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static void StartUsersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<FlatBuffer.Response.JoinRoom> EndJoinRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Response.JoinRoom>(o);
  }
};


}
