// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffer.Response
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LeaveRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static LeaveRoom GetRootAsLeaveRoom(ByteBuffer _bb) { return GetRootAsLeaveRoom(_bb, new LeaveRoom()); }
  public static LeaveRoom GetRootAsLeaveRoom(ByteBuffer _bb, LeaveRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LeaveRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartLeaveRoom(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<FlatBuffer.Response.LeaveRoom> EndLeaveRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffer.Response.LeaveRoom>(o);
  }
};


}
