// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resume struct {
	_tab flatbuffers.Table
}

func GetRootAsResume(buf []byte, offset flatbuffers.UOffsetT) *Resume {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resume{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Resume) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resume) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resume) User() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Resume) Error() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Resume) MutateError(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func ResumeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResumeAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(user), 0)
}
func ResumeAddError(builder *flatbuffers.Builder, error uint32) {
	builder.PrependUint32Slot(1, error, 0)
}
func ResumeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
