// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ActionQueue struct {
	_tab flatbuffers.Table
}

func GetRootAsActionQueue(buf []byte, offset flatbuffers.UOffsetT) *ActionQueue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ActionQueue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ActionQueue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ActionQueue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ActionQueue) Actions(obj *Action, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ActionQueue) ActionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ActionQueueStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ActionQueueAddActions(builder *flatbuffers.Builder, actions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(actions), 0)
}
func ActionQueueStartActionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ActionQueueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
