// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Authentication struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthentication(buf []byte, offset flatbuffers.UOffsetT) *Authentication {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Authentication{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Authentication) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Authentication) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Authentication) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AuthenticationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AuthenticationAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func AuthenticationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
