// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Chat struct {
	_tab flatbuffers.Table
}

func GetRootAsChat(buf []byte, offset flatbuffers.UOffsetT) *Chat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Chat{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Chat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Chat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Chat) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChatStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ChatAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func ChatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
