// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateRoom(buf []byte, offset flatbuffers.UOffsetT) *CreateRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateRoom{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CreateRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func CreateRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func CreateRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
