// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinRoom(buf []byte, offset flatbuffers.UOffsetT) *JoinRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinRoom{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *JoinRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinRoom) Id() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JoinRoom) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func JoinRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func JoinRoomAddId(builder *flatbuffers.Builder, id uint32) {
	builder.PrependUint32Slot(0, id, 0)
}
func JoinRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
