// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KickRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsKickRoom(buf []byte, offset flatbuffers.UOffsetT) *KickRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KickRoom{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *KickRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KickRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KickRoom) User() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KickRoom) MutateUser(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func KickRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KickRoomAddUser(builder *flatbuffers.Builder, user uint64) {
	builder.PrependUint64Slot(0, user, 0)
}
func KickRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
