// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RouteCreate struct {
	_tab flatbuffers.Table
}

func GetRootAsRouteCreate(buf []byte, offset flatbuffers.UOffsetT) *RouteCreate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RouteCreate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RouteCreate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RouteCreate) Table() flatbuffers.Table {
	return rcv._tab
}

func RouteCreateStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RouteCreateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
