// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RouteEnter struct {
	_tab flatbuffers.Table
}

func GetRootAsRouteEnter(buf []byte, offset flatbuffers.UOffsetT) *RouteEnter {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RouteEnter{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RouteEnter) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RouteEnter) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RouteEnter) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RouteEnterStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RouteEnterAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func RouteEnterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
