// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Route struct {
	_tab flatbuffers.Table
}

func GetRootAsRoute(buf []byte, offset flatbuffers.UOffsetT) *Route {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Route{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Route) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Route) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Route) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RouteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RouteAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func RouteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
