// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resume struct {
	_tab flatbuffers.Table
}

func GetRootAsResume(buf []byte, offset flatbuffers.UOffsetT) *Resume {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resume{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Resume) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resume) Table() flatbuffers.Table {
	return rcv._tab
}

func ResumeStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ResumeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
